spring:
  application:
    name: ViKeeper
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/ViKeeper
    username: root
    password: davide98
server:
  port: 8085